# Travis is now container based which doesn't support sudo
sudo: false
language: csharp
solution: PersistenceMap.Interception.sln

notifications:
  email:
#    recipients:
#      - one@example.com
#      - other@example.com
    on_success: never #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always
    
install:
  - nuget restore PersistenceMap.Interception.sln
  - nuget install NUnit.Console -Version 3.0.1 -OutputDirectory testrunner
 
script:
  - xbuild /p:Configuration=Release PersistenceMap.Interception.sln
  
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/adc80b54dde920b03fcd
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always